### ISSUE TITLE
Does this only accept RSS addresses to start with?

### ISSUE THREAD

**Issue by dylan-k** [pamelafox/opml-generator#1]
Formatting a list of RSS feeds into OPML is very useful, but perhaps even more useful would be the ability to create OPML when all you have is a list of website addresses, say, from a blogroll or something. Is that possible?

**Comment by darkzbaron** [comment]
agree. i think you might want to look into this : https://blog.ouseful.info/2010/10/23/feed-detection-from-blog-url-lists-with-opml-output/ i havent tried though
